### ISSUE TITLE
[FEATURE] Admin commands to change players balance

### ISSUE THREAD

**Issue by HollishKid** [pitbox46/monetamoney#4]
First of all, your mod is awesome.
I've been playing around with it and am considering to use it in a modpack.
The one thing I am missing (for integration with other mods) are some admin commands to add/substract/set the amount of money a player has.
If you could consider adding this, that would be really cool!

**Comment by pitbox46** [comment]
I will look into adding more commands in the next release.

**Comment by pitbox46** [comment]
Implemented in code. More commands will be added in the next release.
