### ISSUE TITLE
Error on depositing moneta coins

### ISSUE THREAD

**Issue by HollishKid** [pitbox46/monetamoney#5]
When I obtain the Moneta item (the stack of coins) in creative mode, and then attempt to deposit it into my account, I get the following error in console:
https://pastebin.com/SDx7mYKm

This makes me wonder what the stack of coins item (Moneta) is used for?

**Comment by pitbox46** [comment]
Moneta coins each have a unique ID that is used to prevent duping coins. When you create a stack from the creative screen, it has no ID, so the mod thinks it's a non-authentic coin. I can add a command to add coins to a balance and another one to create a stack of coins in the next update

**Comment by HollishKid** [comment]
Yes, I read about your duping prevention technique and the idea sounds really good!
I posted this issue to highlight the fact that console throws an error (were it could probably silently deny the deposit of the coins).

**Comment by pitbox46** [comment]
Fixed in the code. I will have this feature implemented in the next release.
